trigger:
  branches:
    include:
      - main
      - dev

variables:
  imageRepository: 'afi/demand-planning/wholesale-suite-frontend'
  containerRegistry: 'ashleyfurniture.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '22.x'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'

    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: 'ashleyfurniture'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
